### ISSUE TITLE
Main search does not use labels for recommendations

### ISSUE THREAD

**Issue by MatPopp** [OpenSemanticLab/mediawiki-extensions-OpenSemanticLab#14]
At the moment, for finding labeled terms one needs to know the OSL ID to find the page in the main search bar 

![grafik](https://user-images.githubusercontent.com/27500989/191910377-2bf4fab1-7cab-4910-ab1d-ca18eb3158f5.png)

* The main Search should find labels for recommendations

**Comment by simontaurus** [comment]
fixed with switch to Skin:Citizen (see also https://github.com/StarCitizenTools/mediawiki-skins-Citizen/pull/625)
